server:
  port: 8006
spring:
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    ds2:
      jdbc-url: jdbc:mysql://localhost:3306/ds2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
